deploy:
  provider: firebase
  token:
    secure: ldapkXL6ryqk7gUbA/MAu0QKDwk9iWlnzWbj85+IAS5QSkXQHdyptYn7Zmw59qaIx6VAllPmGZEv93z80j+4t5q5c/VDddaIJeY/XUXaQP9ar1pMtkfqJeNQgtwIMecH4rBJJQff/82Lzd6vouvByiabNJvSPwBkiBpal2HXf9XQOp5Hv/qhE1PMjeTWA5Y3J6j1PJF+/Wo+F3TNsFpam+3BDLQO5KiWuYB/cuM7RRO7gM8BDqDhrkKb3FI+NpPLn7+8+ixE9CxkSuyyU3v7mf5bU3jrozZARxo343gYlDpSw7JSKJ/AAIskFF6n5aM/jUt9DQH9spcDrfrcIQNB8gfAg6UbbhkPpav89XivMh+GrMgCs++p/5hgLzTZ0M4LF83rnQ1gTQjEfK/q3PHmH/8THlqIcewVvw1v+r7I8c+HmU728KWsDdrcgKZvhidOdKY69wKrOLrNhDGkpAZrcxJI40D2JPEkdzcFRaWWVoaZ6kEiI+hrIoh540EECRChe87zo24hbI0dYkZeawRvNhwHNCzTVHWZdQEMh8Ucrrq3Eu/Oh+vGf2ltPst6pIw2jsuUFWl/Q7KrQv4qBrn3uNZqEsFjKpPBLW8+imlmaK7drzIOAIiujy6np7kDCpwG5DXqJmown/uvr+OLb0Zj9jcAy2YR2jJY4poJOUyDSQc=
before_deploy: "echo 'ready?'"
after_deploy: "echo 'YEY'"
