language: node_js
node_js:
  - "5.0"
script:
  - echo "Deploying!!!"
before_script:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --only hosting --token $FIREBASE_TOKEN
os: "windows"