language: node_js
node_js:
  - "8.1"
install:
  - npm install -g firebase-tools
script:
  - npm install
before_script:
  - cd functions
after_script:
  - cd ../
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
